spring:
  datasource:
    url:                jdbc:postgresql://localhost:5432/test
    username:           test
    password:           test
  jpa:
    hibernate:
      ddl-auto:         create-drop
      show-sql:         true

logging:
  level:
    org.papiez:             DEBUG
