spring:
  datasource:
    url:                jdbc:postgresql://localhost:5432/test
    username:           test
    password:           test
  jpa:
    hibernate:
      ddl-auto:         create-drop
      show-sql:         true

logging:
  level:
    org.papiez:             DEBUG

facebook:
  client:
    clientId: 233668646673605
    clientSecret: 33b17e044ee6a4fa383f46ec6e28ea1d
    accessTokenUri: https://graph.facebook.com/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/dialog/oauth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://graph.facebook.com/me
