spring:
  datasource:
    url:                jdbc:postgresql://localhost:5432/testdb
    username:           postgres
    password:
    driverClassName:    org.postgresql.Driver
  jpa:
    show-sql:           true
    database-platform:  org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto:         create-drop

logging:
  level:
    org.papiez:         DEBUG
